/*
 * ** Copyright (C) 2012 Shinichi Ishida, All Rights Reserved.
 * **
 * ** Please see the LICENSE file distributed with this source
 * ** code archive for information covering the modification and
 * ** redistribution of this file and binaries built from it.
 * */

/*
 * $Id: RegExpFilter.H,v 5.0 2010-10-13 08:47:16 sin Exp $
*/

#ifndef RegExpFilter_H
#define RegExpFilter_H

class RegExpFilter
{
	private:
		RegExpFilter();

	public:
};

#endif
